apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      app: udagram-api-feed
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - image: unknow223/udagram-api-feed
        envFrom:
            - secretRef:
                name: udagram-env-secret
            - secretRef:
                name: udagram-aws-secret
            - configMapRef:
                name: udagram-configmap
        name: udagram-api-feed
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1724Mi"
            cpu: "800m" 
      ports:
        - containerPort: 8080  


