apiVersion: v1
kind: Secret
metadata:
 name: udagram-aws-secret #udagram-aws-secret for exemple
type: Opaque
data:
 AWS_ACCSS_KEY_ID: QUtJQTZCMlJaNFpGNVU3UkFMUkE= #base64
 AWS_SECRET_ACCESS_KEY: R2Rzd29vdi9JTmlPL0YvSmF4S2t6K2xMelN0V2V1RmJCc0xBS3ZTVA== #base64
 AWS_SESSION_TOKEN: "" #base64