apiVersion: v1
kind: Secret
metadata:
 name: udagram-aws-secret #udagram-aws-secret for exemple
type: Opaque
data:
 AWS_ACCSS_KEY_ID: QUtJQVRENERISTRFU1A3WUxOTEk= #base64
 AWS_SECRET_ACCESS_KEY: c21FMHZsS09aWjFUN1B4VDFnRlBxbWJVQ0htK1JJQ0xvSlRHanRrMg== #base64
 AWS_SESSION_TOKEN: YOUR-AWS_SESSION_TOKEN #base64