apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  selector:
    matchLabels:
      app: udagram-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - image: unknow223/udagram-frontend
        name: udagram-frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 80
      restartPolicy: Always


