apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-api-user
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - image: unknow223/udagram-api-user
        envFrom:
          - secretRef:
              name: udagram-env-secret
          - secretRef:
              name: udagram-aws-secret
          - configMapRef:
              name: udagram-configmap
        name: udagram-api-user
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1724Mi"
            cpu: "800m"
        ports:
        - containerPort: 8080
        
      restartPolicy: Always


 